// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gswqtiwylwdtiziebsfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzd3F0aXd5bHdkdGl6aWVic2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTYyMzIsImV4cCI6MjA2Mzg5MjIzMn0.DxZz0P2l8AFemVMzbKT45BSt3p4Hv5fe4vkAGkxBjOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);